server:
  port: 8080
  contextPath: /mbox

spring:
  thymeleaf:
    cache: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://114.55.65.26:3306/lj_huijiabao?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    username: linju
    password: linju@focusoo
    validation-query: select 1 from dual
    max-active: 100
    min-idle: 10
    initial-size: 10
    test-while-idle: true
    time-between-eviction-runs-millis: 1800

socketIO:
  port: 10087
  host: mbox.life2car.com

mina:
  port: 10086
  pool: 5
  timeout: 60

logging:
  file: /home/mbox/logs/mbox.log

temp:
  filePath: /home/mbox/temp/

resource:
  path: /home/mbox/resource/
  prefix: http://mbox.life2car.com/mbox-resource/

wkcx:
  url: http://mbox.life2car.com/mbox/
  needUser: true
  webhook: http://huijia.xlinju.cn/wkcx/webhook
  writeLog: true